#-- copyright
# OpenProject management plugin.
# Copyright (C) 2020 Floris Janssens (florisjanssens@outlook.com)
#
# OpenProject is an open source project management software.
# Copyright (C) 2012-2020 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

# This workflow runs Rubocop validations using the latest Rubocop config used on the OpenProject dev branch
name: Rubocop checks

on:
  push:
    branches: [ release/10.6.1 ]
  pull_request:
    branches: [ release/10.6.1s ]


jobs:
  build:
    name: Rubocop Prepare

    runs-on: ubuntu-latest


    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Download the Rubocop config from the OpenProject dev branch
    - name: Get OpenProject Rubocop config
      run: wget https://raw.githubusercontent.com/opf/openproject/dev/.rubocop.yml

    # Run the actual Rubocop check
    - name: Run Rubocop check
      uses: andrewmcodes/rubocop-linter-action@v3.1.0
      with:
        # Define a path to your optional action config file.
        action_config_path: .rubocop.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
